USE [BS]
GO

/****** Object:  Table [dbo].[BS_PESSOA]    Script Date: 01/06/2022 20:17:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BS_PESSOA](
	[PES_ID] [int] IDENTITY(1,1) NOT NULL,
	[PES_NOME] [varchar](100) NOT NULL,
	[PES_DATANASC] [datetime] NOT NULL,
	[PES_TIPOSANG] [char](2) NOT NULL,
	[PES_EMAIL] [varchar](100) NOT NULL,
	[PES_CELULAR] [varchar](100) NOT NULL,
	[PES_CPF] [varchar](100) NOT NULL,
 CONSTRAINT [PK_BS_PESSOA] PRIMARY KEY CLUSTERED 
(
	[PES_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


